package com.example.commander.domain.message;

/**
 * Indicates how a report was triggered.
 *
 * <p>Distinguishes between reports generated by the scheduled batch process, those requested
 * on-demand by a user or external system, and those pushed by an external system with its own
 * data already attached (e.g. the EXT balance use case).
 *
 * <p>Stored in {@code CAMT.ReportCommandAudit.trigger_type} ({@code NVARCHAR(20)}, no
 * check-constraint) for audit and traceability purposes.
 */
public enum TriggerType {
    /** Report was triggered by the scheduled Quartz job. */
    SCHEDULED,

    /** Report was triggered by an on-demand request. */
    ON_DEMAND,

    /** Report was triggered by an external system pushing its own data (e.g. EXT). */
    EXTERNAL
}
