package com.example.camt.contract;

import com.fasterxml.jackson.annotation.JsonProperty;
import java.time.Instant;
import java.util.List;

/**
 * Deserialization target for the JSON messages {@code demo-camt-commander} publishes to its
 * outbound CAMT queues (e.g. {@code CAMT.054C.QUEUE}) — one message per generated report.
 *
 * <p><b>Before using this:</b>
 *
 * <ul>
 *   <li>Change the package ({@code com.example.camt.contract}) to fit your application — it's
 *       a placeholder.
 *   <li>{@code startDateTimeUtc}/{@code endDateTimeUtc} are {@link Instant}, which requires
 *       Jackson's JSR-310 module registered on your {@code ObjectMapper} ({@code
 *       jackson-datatype-jsr310}, or Jackson 3's built-in support). Spring Boot registers this
 *       automatically; a bare Jackson setup needs {@code
 *       objectMapper.registerModule(new JavaTimeModule())} (or the Jackson 3 equivalent).
 *   <li>Fields with no {@code @JsonProperty} value mismatch are annotated anyway, on purpose —
 *       don't rely on your {@code ObjectMapper}'s naming strategy matching these by accident.
 *   <li>Nulls are sent explicitly on the wire (not omitted), so {@code balance}/{@code
 *       settlementAmount}/{@code requestorName} etc. can legitimately deserialize to
 *       {@code null} — don't assume a present key means a non-null value.
 * </ul>
 *
 * <p>Verified against a real message on the wire (2026-08-09):
 *
 * <pre>{@code
 * {"reportId":10000001,"type":"CAMT054C","version":"V02",
 *  "startDateTimeUtc":"2026-07-01T00:00:00Z","endDateTimeUtc":"2026-07-02T00:00:00Z",
 *  "bundled":false,"accountFormat":"IBAN","isPaginated":false,"isEmptyReportAllowed":true,
 *  "triggerType":"ON_DEMAND",
 *  "recipient":{"id":1,"type":"SIGNER_ID","value":"3937231530REP0001","name":"Team Nirvana A"},
 *  "paymentTypes":[{"paymentType":"INSTDOM","accounts":[{"clearingNumber":"89011",
 *    "accountNumber":"504669699","accountBban":"89011504669699","currency":"SEK",
 *    "balance":null,"settlementAmount":null}],"aliases":[]}],
 *  "requestorName":"json-shape-verify","correlationId":"48665a4f-...","id":"FIKASE54C..."}
 * }</pre>
 *
 * @param reportId the source system's report configuration ID
 * @param type the CAMT report type
 * @param version the report version
 * @param startDateTimeUtc reporting window start (inclusive)
 * @param endDateTimeUtc reporting window end — for {@code DAILY}-frequency reports this equals
 *     {@code startDateTimeUtc} (a point-in-time window), not a real range
 * @param bundled {@code true} if this message merges multiple scopes/accounts into one
 *     payload; {@code false} if it covers a single account or alias
 * @param accountFormat the account number format used in this message (e.g. {@code "IBAN"},
 *     {@code "BBAN"})
 * @param isPaginated whether the downstream report itself should be paginated
 * @param isEmptyReportAllowed whether an empty report is a valid outcome for this
 *     configuration, or should be treated as an error
 * @param triggerType how this report was triggered
 * @param recipient the delivery recipient
 * @param paymentTypes the payment type allocations carried by this message — empty for a
 *     "config-only" message (a report configuration with no scopes at all)
 * @param requestorName who initiated the request; {@code null} for scheduled reports
 * @param correlationId groups every message belonging to the same logical report run
 * @param id this message's own unique identifier, generated by the sender
 */
public record ReportMessage(
        @JsonProperty("reportId") int reportId,
        @JsonProperty("type") ReportType type,
        @JsonProperty("version") String version,
        @JsonProperty("startDateTimeUtc") Instant startDateTimeUtc,
        @JsonProperty("endDateTimeUtc") Instant endDateTimeUtc,
        @JsonProperty("bundled") boolean bundled,
        @JsonProperty("accountFormat") String accountFormat,
        @JsonProperty("isPaginated") boolean isPaginated,
        @JsonProperty("isEmptyReportAllowed") boolean isEmptyReportAllowed,
        @JsonProperty("triggerType") TriggerType triggerType,
        @JsonProperty("recipient") Recipient recipient,
        @JsonProperty("paymentTypes") List<PaymentTypeAllocation> paymentTypes,
        @JsonProperty("requestorName") String requestorName,
        @JsonProperty("correlationId") String correlationId,
        @JsonProperty("id") String id) {}
